### ISSUE TITLE
Export of Models to Custom Location

### ISSUE THREAD

**Issue by groakat** [dwaithe/quantifly#2]
Hi Dominic,

Can you provide a way to export the models to a custom location, so that the models can be shared between different computers? (It saved the models, and can load them, but I have no idea where they are)

**Comment by dwaithe** [comment]
Hi groakat,
Currently your models are being exported to:
/Users/peter/.densitycount/models/
You can just copy the contents of this to the equivalent folder on another computer. Hope that helps
Best,
Dominic.
