### ISSUE TITLE
Sorted Filenames in CSV Output File

### ISSUE THREAD

**Issue by groakat** [dwaithe/quantifly#3]
Hi Dominic,

I just looked at one of the CSV files 

```
/Users/peter/.densitycount/models/pv20_1444825553_Test_model_,Filename: ,Frame number: ,Predicted count: ,Corrected count: ,CI 
Wed Oct 14 13:27:49 2015,/Users/peter/tmp/egg_counting_2/M/M-04.png,1,60.827453922587914,84.59936385982185,2.5057905661756052
Wed Oct 14 13:27:49 2015,/Users/peter/tmp/egg_counting_2/M/M-01.png,1,27.645249879946,37.952218086789451,1.0734197871528579
Wed Oct 14 13:27:49 2015,/Users/peter/tmp/egg_counting_2/M/M-02.png,1,28.776612718205755,39.542674440161107,1.1159871212684607
Wed Oct 14 13:27:49 2015,/Users/peter/tmp/egg_counting_2/M/M-03.png,1,28.833166537655636,39.622177123482274,1.118140027109007
```

Is it possible to sort the file names for the output? It makes post-processing easier (particularly if that means to transfer the results into an excel file)

**Comment by dwaithe** [comment]
The images should be export in the order in which they were loaded into the software. If this is not the case please let me know. Otherwise if you open this data in excel you should be able to order the columns using the sort command. I hope that helps.
Best,
Dominic.
